blog/urls.py
from django.urls import path,include
from . import views
from  django.contrib.auth import views as auth_views
from rest_framework import routers
from .api import views as apiviews


router=routers.DefaultRouter()
router.register(r'posts',apiviews.PostViewSet)


app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>', views.post_list,
         name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),

    path('<int:post_id>/<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('share/<int:post_id>/',views.post_share,
         name='post_share'),

    # path('<int:post_id>/share/',views.post_share,
    #      name='post_share'),
    #


    # path('login/',views.user_login,name='login')

    path('login/',auth_views.LoginView.as_view(),
         name='login'),
    path('logout/',auth_views.LogoutView.as_view(),
         name='logout'),
    path('dashboard/',views.dashboard,
         name='dashboard'),

    path('post-add/',views.post_add,
         name='post_add'),
    path('post-edit/<int:post_id>/',views.post_edit,
         name='post_edit'),
    path('post-delete/<int:post_id>/',views.post_delete,
         name='post_delete'),

    path('profile/',views.edit_profile,
         name='edit_profile'),

    path('post_point_list/<int:post_id>/',
         views.post_point_list,
         name='post_point_list'),

    path('post_point_add/<int:post_id>/',
         views.post_point_add,
         name='post_point_add'),

    path('post_point_edit/<int:post_point_id>/',
         views.post_point_edit,
         name='post_point_edit'),

    path('post_point_delete/<int:post_point_id>/',
         views.post_point_delete,
         name='post_point_delete'),

    path('sign-up/',views.sign_up,name='sign-up'),

    path('favourite-posts/',views.favourite_posts,name='favourite_posts'),
    path('add_to_favourite/<int:post_id>/',views.add_to_favourite,name='add_to_favourite'),

    path('delete_from_favourite/<int:post_id>/', views.delete_from_favourite,
         name='delete_from_favourite'),

    path('delete_from_favourite_in_dashboard/<int:post_id>/',
         views.delete_from_favourite_in_dashboard,
         name='delete_from_favourite_in_dashboard'),

    path('api/',include(router.urls)),

    path('my_api/posts/',apiviews.PostList,
         name='post_list'),
    path('my_api/post/<pk>/',apiviews.PostDetail,
         name='post_detail'),

    path('post-edit/<int:post_id>/', views.post_edit,
         name='post_edit'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import Comment, Post, User,PostPoint
class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25,
         widget=forms.TextInput(attrs={
             'class':'form-control',
             'id':'nameInput'}))
    email=forms.EmailField(
        widget=forms.TextInput(
            attrs={"class": "form-control",
                   "id": "InputEmail",
                   "aria-describedby": "emailHelp"
                   }))
    to=forms.EmailField(widget=forms.TextInput(
            attrs={"class": "form-control",
                    'id':'emailTo'}))
    comments=forms.CharField(required=False,
                 widget=forms.Textarea(
                     attrs={"class": "form-control",
                            'id':'comments',
                            'rows':'3'}))

class CommentForm(forms.Form):
    name=forms.CharField(max_length=25,
             widget=forms.TextInput(attrs={
                 'class':'form-control',
                 'id':'nameInput'}))
    email=forms.EmailField(widget=forms.TextInput(attrs={
                 'class':'form-control',
                 'id':'emailInput',
                 'aria-describedby':'EmailHelp'}))
    body=forms.CharField(required=False,
                         widget=forms.Textarea(attrs={
                             'class':'form-control',
                             'id':'comment',
                             'rows':'3'}))




class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'id':'inputLogin',
                'class':'form-control',
                'placeholder':'Логин'}))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'type':'password',
                'id':'inputPassword',
                'class':'form-control',
                'placeholder':'Пароль'}))

class PostAddForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','short_description',
                'image','tags')

class UserEditForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('first_name','last_name',
                'username','email')

class UserCreateForm(forms.ModelForm):
    password=forms.CharField(max_length=40,widget=forms.PasswordInput())
    class Meta:
        model=User
        fields=('first_name','last_name',
                'username','email','password')



class PostPointForm(forms.ModelForm):
    class Meta:
        model=PostPoint
        fields=('post_point_header','post_point_text','post_image')


class SearchForm(forms.Form):
    query=forms.CharField(widget=forms.TextInput(attrs={
        'class':'form-control mr-sm-2',
        'type':'search',
        'placeholder':'Search',
        'aria-label':'Search'
    }))

blog/api/views.py
from rest_framework import viewsets,filters
from ..models import Post,PostPoint
from .serializers import PostSerializer,PostPointSerializer
from django_filters.rest_framework import \
    DjangoFilterBackend
from rest_framework import generics
class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    filter_backends = [filters.SearchFilter,
                       DjangoFilterBackend]
    filterset_fields=['status',]
    search_fields=['title','short_description']

from  rest_framework.response import Response
from rest_framework.decorators import api_view


@api_view(['GET'])
def PostList(request):
    posts=Post.objects.all()
    serializer=PostSerializer(posts,many=True)
    return Response({'post':serializer.data})

@api_view(['GET'])
def PostDetail(request,pk):
    post=Post.objects.get(id=pk)
    serializer=PostSerializer(post)
    post_points=PostPoint.objects.filter(post=post)
    p_p_serializer=PostPointSerializer(post_points
                                       ,many=True)
    return Response({'post':serializer.data,
                 'post_points':p_p_serializer.data})

blog/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from taggit.models import Tag

from .forms import EmailPostForm, CommentForm, LoginForm, PostAddForm, UserEditForm, PostPointForm, SearchForm, \
    UserCreateForm
# Create your views here.
from .models import Post, PostPoint, Comment, User


def post_list(request, tag_slug=None):
    search_form = SearchForm()
    query = None
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']
            try:
                object_list = Post.objects.filter(title__contains=query, status='published')
            except:
                object_list = None
    else:
        object_list = Post.objects.filter(status='published')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag,
                                slug=tag_slug)
        object_list = object_list.filter(
            tags__in=[tag])
    paginator = Paginator(object_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag,
                   'search_form': search_form})


@login_required
def post_detail(request, year, month, day,
                post, post_id):
    post_object = get_object_or_404(Post, slug=post,  # status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day,
                                    id=post_id)
    comments = post_object.comments.filter(active=True)
    new_comment = None
    post_points = PostPoint.objects.filter(
        post=post_object)

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            new_comment = Comment(post=post_object,
                                  name=cd['name'],
                                  email=cd['email'],
                                  body=cd['body'])
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post_object.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(
        status='published',
        tags__in=post_tags_ids).exclude(
        id=post_object.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')).order_by(
        '-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html',
                  {'post': post_object,
                   'post_points': post_points,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


@login_required
def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id,
                             status='published')
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = '{} ({}) рекомендует вам прочитать {}'.format(
                cd['name'], cd['email'], post.title)
            message = '''Прочитай  "{}" по {}  
Коментарий: {} '''.format(post.title, post_url, cd['comments'])
            send_mail(subject, message, 'admin@myblog.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request,
                  'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent})


def user_login(request):
    users = User.objects.all()
    for u in users:
        print(u.email)
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse(
                        'Пользователь авторизирован')
                else:
                    return HttpResponse(
                        'Аккаунт заблокирован')
            else:
                return HttpResponse('Неверные данные')
    else:
        form = LoginForm()
    return render(request,
                  'blog/account/login.html',
                  {'form': form})


@login_required
def dashboard(request):
    user = request.user
    posts_pub = Post.objects.filter(author=user,
                                    status='published')
    posts_draft = Post.objects.filter(author=user,
                                      status='draft')

    return render(request,
                  'blog/account/dashboard.html',
                  {'section': 'dashboard',
                   'posts_pub': posts_pub,
                   'posts_draft': posts_draft
                   })


@login_required
def post_add(request):
    user = request.user
    if request.method == 'POST':
        form = PostAddForm(request.POST,
                           request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = user
            post.save()
            for tag in form.cleaned_data['tags']:
                post.tags.add(tag)

            # return redirect('blog:dashboard')
    else:
        form = PostAddForm()
    return render(request,
                  'blog/account/post_add.html',
                  {'form': form, })


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post_edit_form = PostAddForm(instance=post)
    if request.method == 'POST':
        post_edit_form = PostAddForm(request.POST,
                                     instance=post)
        if post_edit_form.is_valid():
            post_edit_form.save()
    return render(request,
                  'blog/account/post_edit.html',
                  {'form': post_edit_form,
                   'post': post})


@login_required
def post_delete(requst, post_id):
    try:
        post = get_object_or_404(Post,
                                 id=post_id)
        post.delete()
        return redirect('blog:dashboard')
    except Post.DoesNotExist:
        return redirect('blog:dashboard')


@login_required
def edit_profile(request):
    user_form = UserEditForm(
        instance=request.user)
    if request.method == 'POST':
        user_form = UserEditForm(
            request.POST,
            instance=request.user)
        if user_form.is_valid():
            user_form.save()
    return render(request,
                  'blog/account/profile.html',
                  {'user_form': user_form})


@login_required
def post_point_list(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    post_points = PostPoint.objects.filter(
        post=post)
    return render(request,
                  'blog/account/post_points.html',
                  {'post': post,
                   'post_points': post_points})


@login_required
def post_point_edit(request, post_point_id):
    post_point = get_object_or_404(PostPoint, id=post_point_id)
    post = get_object_or_404(Post, id=post_point.post.id)
    post_point_edit_form = PostPointForm(instance=post_point)
    if request.method == 'POST':
        post_point_edit_form = PostPointForm(request.POST,
                                             instance=post_point)
        if post_point_edit_form.is_valid():
            post_point_edit_form.save()
    return render(request, 'blog/account/post_point_edit.html',
                  {'form': post_point_edit_form,
                   'post_point': post_point,
                   'post': post})


# TODO: форма поиска,
# TODO: добавить  форму регитсрации,
@login_required
def post_point_delete(request, post_point_id):
    try:
        post_point = get_object_or_404(PostPoint,
                                       id=post_point_id)
        post_point.delete()
        return redirect('blog:post_point_list', post_id=post_point.post.id)
    except PostPoint.DoesNotExist:
        return redirect('blog:post_list')


@login_required
def post_point_add(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostPointForm()

    if request.method == 'POST':
        form = PostPointForm(request.POST,
                             request.FILES)
        if form.is_valid():
            post_point = form.save(commit=False)
            post_point.post = post
            post_point.save()

    return render(request, 'blog/account/post_point_add.html', {'form': form,
                                                                'post': post})


def sign_up(request):
    user_form = UserCreateForm()
    if request.method == 'POST':
        user_form = UserCreateForm(request.POST)
        if user_form.is_valid():
            new_user = User.objects.create_user(**user_form.cleaned_data)
            new_user.save()
            login(request, authenticate(username=user_form.cleaned_data['username'],
                                        password=user_form.cleaned_data['password']))

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load  bootstrap %}

{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}


    <div class="container my-3">
        <div class="card-deck">
            <div class="card">
                <div class="row">
                        <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top detail-image-size" alt="...">

                        <div class="favourite">
                            {% if post in request.user.fav_posts.all%}
                                <a href="{% url 'blog:delete_from_favourite' post.id %}">
                                    <img src="{% static 'img/star_yellow.png' %}" alt="">
                                </a>
                            {% else %}
                                <a href="{% url 'blog:add_to_favourite' post.id %}">
                                    <img src="{% static 'img/star_empty.png' %}" alt="">
                                </a>
                            {% endif %}
                        </div>
                 </div>
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <span>
                        <a href="{% url 'blog:post_share' post.id %}">
                            Поделиться рецептом
                        </a>
                    </span>
                    <p class="card-text">{{ post.short_description }}</p>
                </div>
                {% for post_point in post_points %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post_point.post_point_header}}</h5>
                        {% if post_point.post_image %}
                            <img src="{{ MEDIA_URL }}{{ post_point.post_image.url }}" class="card-img-top" alt="..."
                            style="width: 500px">
                        {% endif %}
                        {% if post_point.post_point_header.lower == "ингредиенты" %}
                            <pre class="card-text">{{ post_point.post_point_text }}</pre>
                        {% else %}
                            <p class="card-text">{{ post_point.post_point_text }}</p>
                        {% endif %}

                    </div>
                {% endfor %}
                <div class="card-footer">
                    <small class="text-muted">Опубликовано {{ post.publish }}. Автор {{ post.author }}</small>
                </div>

            
            

                {% if similar_posts %}
                    <h2 class="text-center mb-3">Похожие статьи</h2>
                    <div class="row row-cols-1 row-cols-md-3">
                        {% for post in similar_posts %}
                              <div class="col mb-4">
                                <div class="card h-100">
                                  <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                                  <div class="card-body">
                                    <h5 class="card-title">
                                        <a href="{{post.get_absolute_url}}">
                                            {{ post.title|truncatechars:70 }}
                                        </a>
                                    </h5>
                                  </div>
                                </div>
                              </div>
                        {% empty %}
                        {% endfor %}
                    </div>
                {% endif %}

            
                {% with comments.count as total_comments  %}
                    <h2 class="text-center">
                        Коментариев :{{ total_comments }}
                    </h2>
                {% endwith %}
                {% for comment in comments %}
                    <div class="card border-dark mb-3" >
                      <div class="card-header"><b>{{ forloop.counter }}. </b> {{ comment.name }},   <b>E-mail</b> {{ comment.email }}</div>
                       <div class="card-body  text-dark">
                        <p class="card-text">{{ comment.body }}</p>
                      </div>
                    </div>
                {% endfor %}
                <div class="m5">
                    {% if new_comment %}
                        <h2>Ваш комментарий добавлен</h2>
                    {% else %}
                        <h2 class="text-center">Добавить комментарий</h2>


                        <div class="container">
                            <form action="." method="post">
                                {{ comment_form.name|bootstrap }}
                                {{ comment_form.email|bootstrap }}
                                {{ comment_form.body|bootstrap }}

                                <button type="submit"
                                        class="btn btn-primary">
                                    Добавить комментарий
                                </button>
                                {% csrf_token %}
                            </form>
                        </div>



                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/post/list.html
{%extends 'blog/base.html'%}

{%block title%} My blog {%endblock%}

{% block search_form %}
        <form class="form-inline my-2 my-lg-0 search-form">
            {{ search_form }}
            {% csrf_token %}
            <button class="btn btn-dark my-2 my-sm-0" type="submit">Search</button>
        </form>
{% endblock %}


{%block content%}
    <h1 class="title text-center my-3">Кулинарная книга</h1>
    <div class="container">
        {% if tag %}
            <h3 class="text-center">Статьи по тегу:
                {{ tag.name }}
            </h3>
        {% endif %}
        <div class="card-deck">
            <div class="row row-cols-3 row-cols-md-3">
                {% for post in posts %}
                        <div class="col mb-4" >
                            <div class="card" style="height: 100%">
                                <a href="{{ post.get_absolute_url }}">
                                    <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                                </a>
                                <div class="card-body">
                                    <a href="{{ post.get_absolute_url }}">
                                        <h5 class="card-title">{{ post.title }}</h5 >
                                    </a>
                                    <p class="card-text">{{ post.short_description }}</p>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">Опубликовано {{ post.publish }}. Автор {{ post.author }}</small>
{#                                    <p>Теги: {{ post.tags.all|join:", " }}</p>#}
                                    <p> Теги:
                                        {% for tag in post.tags.all %}
                                            <a href="{%  url "blog:post_list_by_tag" tag.slug  %}">
                                                {{ tag.name }}
                                            </a>
                                            {% if not forloop.last %}
                                                ,
                                            {% endif %}
                                        {% endfor %}

                                    </p>
                                </div>
                            </div>
                        </div>
                {% endfor %}
            </div>
        </div>
{#    {% include 'paginations.html' with page=page_obj %}#}
    {% include 'paginations.html' with page=posts %}
    </div>

{%endblock%}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}
    Поделиться постом
{% endblock %}
{% block content %}
    <div class="container">
        {% if sent %}
            <h1>E-mail успешно отправлен</h1>
            <p>"{{ post.title }}" Было успешно отправлено
                {{ form.cleaned_data.to }}
            </p>
        {% else %}
            <h1>"{{ post.title }}"  Будет отправленo</h1>
            <form action="." method="post">
                <div class="form-group">
                    <label for="nameInput">Имя</label>
                    {{ form.name }}
                </div>    
                <div class="form-group">
                     <label for="InputEmail">Ваш E-mail</label>
                    {{ form.email }}
                </div>
                <div class="form-group">
                     <label for="EmailTo">E-mail получателя</label>
                    {{ form.to }}
                </div>
                <div class="form-group">
                     <label for="comment">Комментарий</label>
                    {{ form.comments }}
                </div>
                <button type="submit" class="btn btn-primary" value="send e-mail">
                    Отправить
                </button>

                {% csrf_token %}
            </form>
        {% endif %}
    </div>

{% endblock %}